/*
 *  ToneTest -- play known tones at known sample rates through the Sound Manager.
 *
 *  Everything up to now has been verified against the boot chime, which the ROM plays at one
 *  fixed rate, and against SysBeep, which is one sound at one rate.  Neither says whether
 *  ordinary audio at other rates comes out at the right pitch.  That matters here because
 *  PrimeTime II has no sample rate converter: the chip runs at a fixed 22254.5Hz and anything
 *  at another rate has to be resampled by the Sound Manager in software.  If that is modelled
 *  wrongly, an 11kHz sound plays at the wrong speed while a 22kHz one sounds fine.
 *
 *  Each tone is a sine of known frequency, so the output can be checked by measuring the
 *  fundamental in a WAV capture: the pitch should come back unchanged whatever rate it was
 *  sampled at.  Tones are spaced widely so they separate cleanly.
 *
 *  Run from Startup Items; see cordyceps-notes/CORDYCEPS-ASC.md.
 */

#include <Sound.h>
#include <Events.h>

/* Retro68's multiversal headers declare the Sound Manager calls and structures but not
   these constants, so spell them out.  The two rate values are the same 16.16 constants the
   Mac OS ROM keeps in its table at $4030456C. */
#ifndef kMiddleC
#define kMiddleC        60
#endif
#ifndef initMono
#define initMono        0x0080
#endif
#ifndef rate22khz
#define rate22khz       0x56EE8BA3UL
#endif
#ifndef rate11khz
#define rate11khz       0x2B7745D1UL
#endif

#define MAXSAMP 24000

static unsigned char gSamples[MAXSAMP];
static SoundHeader gHdr;

static void Wait(long ticks)
{
	const long deadline = TickCount() + ticks;
	while (TickCount() < deadline)
	{
	}
}

/* Fill the buffer with a sine of freqHz at rateHz, 8-bit offset binary as stdSH wants.
   No libm: the sine is generated by the standard two-term recurrence, which is plenty
   accurate over a few thousand samples and keeps the binary small. */
static long MakeSine(long rateHz, long freqHz, long nsamp)
{
	/* s[n+1] = k*s[n] - s[n-1], k = 2*cos(2*pi*f/rate), in 16.16 fixed point */
	long i;
	double w = 6.283185307179586 * (double)freqHz / (double)rateHz;
	/* cos via its series is awkward; use the half-angle identity on a coarse table instead */
	double c = 1.0, term = 1.0;
	double x2 = w * w;
	for (i = 1; i <= 8; i++)
	{
		term = -term * x2 / (double)((2 * i - 1) * (2 * i));
		c += term;
	}
	{
		double s0 = 0.0, s1 = 0.0, k = 2.0 * c, sn;
		/* seed with sin(w) via the same series */
		double s = w, t = w;
		for (i = 1; i <= 8; i++)
		{
			t = -t * x2 / (double)((2 * i) * (2 * i + 1));
			s += t;
		}
		s1 = s;
		for (i = 0; i < nsamp; i++)
		{
			double v = (i == 0) ? s0 : ((i == 1) ? s1 : 0.0);
			if (i >= 2)
			{
				sn = k * s1 - s0;
				s0 = s1;
				s1 = sn;
				v = sn;
			}
			else if (i == 1)
			{
				/* s0/s1 already seeded */
			}
			if (v > 1.0) v = 1.0;
			if (v < -1.0) v = -1.0;
			gSamples[i] = (unsigned char)(128 + (int)(v * 100.0));
		}
	}
	return nsamp;
}

static void PlayTone(SndChannelPtr chan, unsigned long rateFixed, long rateHz, long freqHz)
{
	SndCommand cmd;
	long n = rateHz / 2;            /* half a second */

	if (n > MAXSAMP) n = MAXSAMP;
	MakeSine(rateHz, freqHz, n);

	gHdr.samplePtr = (Ptr)gSamples;
	gHdr.length = n;
	gHdr.sampleRate = rateFixed;
	gHdr.loopStart = 0;
	gHdr.loopEnd = 0;
	gHdr.encode = stdSH;
	gHdr.baseFrequency = kMiddleC;

	cmd.cmd = bufferCmd;
	cmd.param1 = 0;
	cmd.param2 = (long)&gHdr;
	SndDoImmediate(chan, &cmd);

	Wait(60);                        /* let it finish */
}

int main(void)
{
	SndChannelPtr chan = 0;

	Wait(150);

	if (SndNewChannel(&chan, sampledSynth, initMono, 0) != noErr)
	{
		SysBeep(60);                 /* a long beep means the channel could not be opened */
		return 0;
	}

	/* marker: one short beep, then the tones */
	SysBeep(10);
	Wait(120);

	PlayTone(chan, rate22khz,   22254, 440);   Wait(90);
	PlayTone(chan, rate11khz,   11127, 440);   Wait(90);
	PlayTone(chan, rate22khz,   22254, 1000);  Wait(90);
	PlayTone(chan, rate11khz,   11127, 1000);  Wait(90);

	SndDisposeChannel(chan, true);
	Wait(60);
	return 0;
}
